var quotes = [
'That was a nice click... I guess.',
'Wimpy.',
'That click <em>sucked</em>.',
'Not good enough.',
'Click <a href="literal.html">lighter</a> this time!',
'Click <a href="literal.html">harder</a> this time!',
'I barely felt that!',
'Meh.',
'That\'s fine... lol jk.',
'You are <b>terrible</b> at clicking.',
'Boooooooooooo!',
'I am... <em>utterly disgusted</em> by your clicking skills.',
'Disgraceful.',
'You should go hone up on your clicking skills.',
'Getting better... <em>almost</em>.',
'Not quite there yet.',
'Nope.',
'Please learn better clicking.',
'Do I, a computer, need to tell <em>you</em> how to <b>click</b>!?',
'That was a nice click... I guess.',
'Wimpy.',
'That click <em>sucked</em>.',
'Not good enough.',
'Click <a href="literal.html">lighter</a> this time!',
'Click <a href="literal.html">harder</a> this time!',
'I barely felt that!',
'Meh.',
'That\'s fine... lol jk.',
'You are <b>terrible</b> at clicking.',
'Boooooooooooo!',
'I am... <em>utterly disgusted</em> by your clicking skills.',
'Disgraceful.',
'You should go hone up on your clicking skills.',
'Getting better... <em>almost</em>.',
'Not quite there yet.',
'Nope.',
'Please learn better clicking.',
'Do I, a computer, need to tell <em>you</em> how to <b>click</b>!?',
'That was a nice click... I guess.',
'Wimpy.',
'That click <em>sucked</em>.',
'Not good enough.',
'Click <a href="literal.html">lighter</a> this time!',
'Click <a href="literal.html">harder</a> this time!',
'I barely felt that!',
'Meh.',
'That\'s fine... lol jk.',
'You are <b>terrible</b> at clicking.',
'Boooooooooooo!',
'I am... <em>utterly disgusted</em> by your clicking skills.',
'Disgraceful.',
'You should go hone up on your clicking skills.',
'Getting better... <em>almost</em>.',
'Not quite there yet.',
'Nope.',
'Please learn better clicking.',
'Do I, a computer, need to tell <em>you</em> how to <b>click</b>!?',
'Amazing! A good click! See, I knew you could do it! :D (lol i\'m still joking)',
'No. Just... no.',
'That was a nice click... I guess.',
'Wimpy.',
'That click <em>sucked</em>.',
'Not good enough.',
'Click <a href="literal.html">lighter</a> this time!',
'Click <a href="literal.html">harder</a> this time!',
'I barely felt that!',
'Meh.',
'That\'s fine... lol jk.',
'You are <b>terrible</b> at clicking.',
'Boooooooooooo!',
'I am... <em>utterly disgusted</em> by your clicking skills.',
'Disgraceful.',
'You should go hone up on your clicking skills.',
'Getting better... <em>almost</em>.',
'Not quite there yet.',
'Nope.',
'Please learn better clicking.',
'Do I, a computer, need to tell <em>you</em> how to <b>click</b>!?',
'That was a nice click... I guess.',
'Wimpy.',
'That click <em>sucked</em>.',
'Not good enough.',
'Click <a href="literal.html">lighter</a> this time!',
'Click <a href="literal.html">harder</a> this time!',
'I barely felt that!',
'Meh.',
'That\'s fine... lol jk.',
'You are <b>terrible</b> at clicking.',
'Boooooooooooo!',
'I am... <em>utterly disgusted</em> by your clicking skills.',
'Disgraceful.',
'You should go hone up on your clicking skills.',
'Getting better... <em>almost</em>.',
'Not quite there yet.',
'Nope.',
'Please learn better clicking.',
'Do I, a computer, need to tell <em>you</em> how to <b>click</b>!?',
'That was a nice click... I guess.',
'Wimpy.',
'That click <em>sucked</em>.',
'Not good enough.',
'Click <a href="literal.html">lighter</a> this time!',
'Click <a href="literal.html">harder</a> this time!',
'I barely felt that!',
'Meh.',
'That\'s fine... lol jk.',
'You are <b>terrible</b> at clicking.',
'Boooooooooooo!',
'I am... <em>utterly disgusted</em> by your clicking skills.',
'Disgraceful.',
'You should go hone up on your clicking skills.',
'Getting better... <em>almost</em>.',
'Not quite there yet.',
'Nope.',
'Please learn better clicking.',
'Do I, a computer, need to tell <em>you</em> how to <b>click</b>!?',
'No. Just... no.'

];

function newTip() {
    var _0xe615x3 = Math['floor'](Math['random']() * (quotes['length']));
    document['getElementById']('quoteDisplay')['innerHTML'] = quotes[_0xe615x3]
}